"""
Setuptools packaging configuration for koan.
"""

# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: Copyright 2015 Jorgen Maas <jorgen.maas@gmail.com>

from setuptools import setup

_version_template = (
    "# Auto-generated by setuptools_scm — do not edit\n"
    '__version__ = "{version}"\n'
    '__gitstamp__ = "{scm_version.node}"\n'
    '__gitdate__ = "{scm_version.node_date}"\n'
    '__builddate__ = "{scm_version.time}"\n'
)

setup(
    use_scm_version={
        "write_to": "koan/_version.py",
        "write_to_template": _version_template,
        "fallback_version": "3.0.2",
    },
    packages=["koan"],
    scripts=["bin/koan", "bin/cobbler-register"],
)
