name: Testing Koan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/opensuse/tumbleweed:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install package deps
        run: zypper -n in --no-recommends git tar python3 python3-devel python3-wheel python3-pip python3-libvirt-python gcc make
      - name: Install dependencies
        run: pip3 install --break-system-packages .[lint,test]
      - name: Run tests
        run: pytest --cov=./koan
